"use client";

import { AuthenticatedPage } from "@/components/authenticated-page";
import { apiJson } from "@/lib/api";
import { AlertTriangle, CheckCircle2, FileWarning, LoaderCircle, RefreshCw, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useEffect, useEffectEvent, useState } from "react";

type Health = { generated_at: string; checks: Record<string, number>; attention_needed: string[]; ok: boolean };
type Passport = { user_id: number; nanny_id: number; name: string; email: string; nationality?: string | null; passport_expiry?: string | null; days_remaining?: number | null; passport_uploaded: boolean; passport_approved: boolean; replacement_pending: boolean; is_suspended: boolean; suspension_reason?: string | null; state: string };
type PassportResult = { results: Passport[]; counts: Record<string, number> };
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());

export default function OperationsPage() { return <AuthenticatedPage>{(role) => role === "admin" ? <Operations/> : <div className="card mx-auto max-w-xl p-8 text-center"><h1 className="text-2xl font-bold">Team access only</h1></div>}</AuthenticatedPage>; }

function Operations() {
  const [health, setHealth] = useState<Health | null>(null); const [passports, setPassports] = useState<PassportResult | null>(null); const [filter, setFilter] = useState("attention"); const [loading, setLoading] = useState(true); const [running, setRunning] = useState(false); const [message, setMessage] = useState("");
  async function load() { setLoading(true); try { const [healthData, passportData] = await Promise.all([apiJson<Health>("/admin/ops/health"), apiJson<PassportResult>("/admin/passport-compliance")]); setHealth(healthData); setPassports(passportData); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to load operational safety data."); } finally { setLoading(false); } }
  const loadInitial = useEffectEvent(load); useEffect(() => { Promise.resolve().then(() => loadInitial()); }, []);
  async function runCompliance() { setRunning(true); setMessage(""); try { const result = await apiJson<{ warned: number; suspended: number }>("/admin/passport-compliance/run", { method: "POST" }); setMessage(`Compliance check complete: ${result.warned} warnings sent and ${result.suspended} accounts suspended.`); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to run passport compliance."); } finally { setRunning(false); } }
  const visible = (passports?.results || []).filter((row) => filter === "all" || (filter === "attention" ? row.state !== "valid" : row.state === filter));
  return <div className="mx-auto max-w-[1400px]"><div className="eyebrow">Risk, safety & compliance</div><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="display text-4xl sm:text-5xl">Safety centre.</h1><p className="mt-3 text-[var(--muted)]">Surface operational failures and keep foreign nanny documentation valid.</p></div><button className="btn-secondary" disabled={loading} onClick={() => void load()}><RefreshCw className={loading ? "animate-spin" : ""} size={17}/>Refresh</button></div>
    {message && <div className="mt-5 rounded-2xl bg-[var(--blue-pale)] p-4 font-semibold">{message}</div>}
    {loading && !health ? <div className="flex min-h-64 items-center justify-center"><LoaderCircle className="animate-spin"/></div> : <>
      <section className="mt-7"><div className="mb-4 flex items-center gap-3"><ShieldAlert className="text-[var(--blue-dark)]"/><h2 className="text-2xl font-bold">Operational health</h2>{health && <span className={`pill ${health.ok ? "!text-emerald-700" : "!text-amber-700"}`}>{health.ok ? "All clear" : `${health.attention_needed.length} areas need attention`}</span>}</div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(health?.checks || {}).map(([key, value]) => { const attention = health?.attention_needed.includes(key); return <div className={`card p-5 ${attention ? "border-amber-300 bg-amber-50/60" : ""}`} key={key}><div className="flex items-start justify-between gap-3"><span className={`flex h-10 w-10 items-center justify-center rounded-full ${attention ? "bg-amber-100 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}>{attention ? <AlertTriangle size={19}/> : <CheckCircle2 size={19}/>}</span><b className="text-3xl">{value}</b></div><h3 className="mt-4 font-bold">{label(key)}</h3></div>; })}</div></section>
      <section className="card mt-7 overflow-hidden"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-[var(--line)] p-6"><div><div className="eyebrow">Foreign nanny compliance</div><h2 className="mt-2 text-2xl font-bold">Passport queue</h2><p className="mt-1 text-sm text-[var(--muted)]">Renewals require both the new document and expiry date to be approved.</p></div><div className="flex flex-wrap gap-2"><select className="field max-w-56" value={filter} onChange={(e) => setFilter(e.target.value)}><option value="attention">Needs attention</option><option value="awaiting_approval">Awaiting approval</option><option value="expiring">Expiring within 90 days</option><option value="expired">Expired</option><option value="suspended">Suspended</option><option value="missing_expiry">Missing expiry</option><option value="all">All foreign nannies</option></select><button className="btn-primary" disabled={running} onClick={() => void runCompliance()}>{running ? <LoaderCircle className="animate-spin" size={17}/> : <FileWarning size={17}/>}Run compliance check</button></div></header><div className="divide-y divide-[var(--line)]">{visible.length ? visible.map((row) => <article className="grid gap-4 p-6 lg:grid-cols-[1fr_auto]" key={row.user_id}><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-extrabold">{row.name}</h3><span className={`pill ${row.state === "valid" ? "!text-emerald-700" : row.is_suspended ? "!text-red-700" : "!text-amber-700"}`}>{label(row.state)}</span></div><p className="mt-1 text-sm text-[var(--muted)]">{row.email} · {row.nationality || "Nationality unavailable"}</p><div className="mt-3 flex flex-wrap gap-x-6 gap-y-2 text-sm"><span>Expiry: <b>{row.passport_expiry || "Missing"}</b></span><span>{row.days_remaining == null ? "Expiry not supplied" : row.days_remaining > 0 ? `${row.days_remaining} days remaining` : `${Math.abs(row.days_remaining)} days overdue`}</span><span>Document: <b>{row.passport_uploaded ? "Uploaded" : "Missing"}</b></span><span>Approval: <b>{row.passport_approved ? "Approved" : "Required"}</b></span></div>{row.suspension_reason && <p className="mt-3 text-sm font-semibold text-red-700">{row.suspension_reason}</p>}</div><Link className="btn-secondary self-center" href={`/users?user=${row.user_id}`}>Open candidate file</Link></article>) : <div className="p-12 text-center"><CheckCircle2 className="mx-auto text-emerald-600" size={34}/><h3 className="mt-4 text-xl font-bold">No passport records in this queue</h3></div>}</div></section>
    </>}</div>;
}
