"use client";

import { AuthenticatedPage } from "@/components/authenticated-page";
import { apiJson } from "@/lib/api";
import { ClipboardList, LoaderCircle, Search, X } from "lucide-react";
import { useEffect, useEffectEvent, useState } from "react";

type AuditRow = { id: number; created_at: string; actor_user_id?: number | null; actor_role?: string | null; actor_email?: string | null; target_user_id?: number | null; target_email?: string | null; entity?: string | null; entity_id?: string | null; action?: string | null; changed_fields?: string[] | string | null };
type AuditDetail = AuditRow & { before_json?: unknown; after_json?: unknown; ip?: string | null; user_agent?: string | null };
const pretty = (value: unknown) => JSON.stringify(value ?? {}, null, 2);

export default function AuditPage() { return <AuthenticatedPage>{(role) => role === "admin" ? <Audit /> : <div className="card mx-auto max-w-xl p-8 text-center"><h1 className="text-2xl font-bold">Team access only</h1></div>}</AuthenticatedPage>; }

function Audit() {
  const [rows, setRows] = useState<AuditRow[]>([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState(""); const [entity, setEntity] = useState(""); const [action, setAction] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const [detail, setDetail] = useState<AuditDetail | null>(null); const [message, setMessage] = useState("");
  async function load() { setLoading(true); setMessage(""); const params = new URLSearchParams({ limit: "100" }); if (query.trim()) params.set("q", query.trim()); if (entity.trim()) params.set("entity", entity.trim()); if (action.trim()) params.set("action", action.trim()); if (from) params.set("from_ts", new Date(`${from}T00:00:00`).toISOString()); if (to) params.set("to_ts", new Date(`${to}T23:59:59`).toISOString()); try { const data = await apiJson<{ total: number; results: AuditRow[] }>(`/admin/audit-logs?${params}`); setRows(data.results || []); setTotal(data.total || 0); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to load audit logs."); } finally { setLoading(false); } }
  const loadInitial = useEffectEvent(load);
  useEffect(() => { Promise.resolve().then(() => loadInitial()); }, []);
  async function open(id: number) { try { setDetail(await apiJson<AuditDetail>(`/admin/audit-logs/${id}`)); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to open this audit record."); } }
  return <div className="mx-auto max-w-[1500px]"><div className="eyebrow">Governance & traceability</div><h1 className="display mt-2 text-4xl sm:text-5xl">Audit logs.</h1><p className="mt-3 text-[var(--muted)]">See who changed what, when it changed, and the recorded before-and-after state.</p>
    <form className="card mt-7 grid gap-4 p-4 lg:grid-cols-[1.5fr_1fr_1fr_.8fr_.8fr_auto]" onSubmit={(e) => { e.preventDefault(); void load(); }}><label className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="field !pl-11" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Email, entity or record ID"/></label><input className="field" value={entity} onChange={(e) => setEntity(e.target.value)} placeholder="Entity, e.g. bookings"/><input className="field" value={action} onChange={(e) => setAction(e.target.value)} placeholder="Action"/><input className="field" type="date" value={from} onChange={(e) => setFrom(e.target.value)}/><input className="field" type="date" value={to} onChange={(e) => setTo(e.target.value)}/><button className="btn-primary" type="submit">Search</button></form>
    {message && <div role="alert" className="mt-5 rounded-2xl bg-red-50 p-4 text-red-800">{message}</div>}
    <section className="card mt-6 overflow-hidden"><header className="flex items-center justify-between border-b border-[var(--line)] p-5"><div className="flex items-center gap-3"><ClipboardList className="text-[var(--blue-dark)]"/><b>{total} matching events</b></div><span className="text-xs text-[var(--muted)]">Showing latest {rows.length}</span></header>{loading ? <div className="flex min-h-64 items-center justify-center"><LoaderCircle className="animate-spin"/></div> : <div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-[var(--blue-pale)] text-xs uppercase text-[var(--muted)]"><tr>{["When", "Actor", "Target", "Record", "Action", "Changed"].map((heading) => <th className="p-4" key={heading}>{heading}</th>)}</tr></thead><tbody>{rows.map((row) => <tr className="cursor-pointer border-t border-[var(--line)] hover:bg-slate-50" onClick={() => void open(row.id)} key={row.id}><td className="whitespace-nowrap p-4">{new Date(row.created_at).toLocaleString("en-ZA")}</td><td className="p-4"><b>{row.actor_email || `User #${row.actor_user_id || "system"}`}</b><div className="capitalize text-[var(--muted)]">{row.actor_role || "system"}</div></td><td className="p-4">{row.target_email || (row.target_user_id ? `User #${row.target_user_id}` : "—")}</td><td className="p-4"><b>{row.entity || "—"}</b><div className="text-[var(--muted)]">#{row.entity_id || "—"}</div></td><td className="p-4 font-bold">{(row.action || "—").replaceAll("_", " ")}</td><td className="max-w-72 truncate p-4 text-[var(--muted)]">{Array.isArray(row.changed_fields) ? row.changed_fields.join(", ") : row.changed_fields || "—"}</td></tr>)}</tbody></table>{!rows.length && <div className="p-12 text-center text-[var(--muted)]">No audit events match these filters.</div>}</div>}</section>
    {detail && <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/35" onMouseDown={(e) => { if (e.currentTarget === e.target) setDetail(null); }}><aside className="h-full w-full max-w-3xl overflow-y-auto bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-start justify-between border-b border-[var(--line)] bg-white p-6"><div><div className="eyebrow">Audit event #{detail.id}</div><h2 className="mt-2 text-2xl font-bold">{(detail.action || "Recorded change").replaceAll("_", " ")}</h2><p className="mt-1 text-sm text-[var(--muted)]">{detail.entity} #{detail.entity_id} · {new Date(detail.created_at).toLocaleString("en-ZA")}</p></div><button className="btn-quiet !px-3" onClick={() => setDetail(null)} aria-label="Close"><X/></button></header><div className="grid gap-6 p-6"><div className="card grid gap-4 p-5 sm:grid-cols-2"><div><span className="text-xs font-bold uppercase text-[var(--muted)]">Actor</span><p className="mt-1 font-bold">{detail.actor_role || "System"} #{detail.actor_user_id || "—"}</p></div><div><span className="text-xs font-bold uppercase text-[var(--muted)]">Target</span><p className="mt-1 font-bold">User #{detail.target_user_id || "—"}</p></div><div><span className="text-xs font-bold uppercase text-[var(--muted)]">IP address</span><p className="mt-1">{detail.ip || "Not recorded"}</p></div><div><span className="text-xs font-bold uppercase text-[var(--muted)]">Changed fields</span><p className="mt-1">{Array.isArray(detail.changed_fields) ? detail.changed_fields.join(", ") : detail.changed_fields || "None listed"}</p></div></div><JsonBlock title="Before" value={detail.before_json}/><JsonBlock title="After" value={detail.after_json}/></div></aside></div>}
  </div>;
}

function JsonBlock({ title, value }: { title: string; value: unknown }) { return <section><h3 className="mb-3 text-lg font-bold">{title}</h3><pre className="max-h-[420px] overflow-auto rounded-2xl bg-[#18324a] p-5 text-xs leading-6 text-slate-100">{pretty(value)}</pre></section>; }
