"""baseline schema

Revision ID: 6b5e6b603b3a
Revises: 
Create Date: 2026-07-19 12:27:15.952826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5e6b603b3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_maps_api_key', sa.Text(), nullable=True),
    sa.Column('google_calendar_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nanny_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pricing_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday_half_day', sa.Integer(), nullable=False),
    sa.Column('weekday_full_day', sa.Integer(), nullable=False),
    sa.Column('weekend_half_day', sa.Integer(), nullable=False),
    sa.Column('weekend_full_day', sa.Integer(), nullable=False),
    sa.Column('sleepover_add', sa.Integer(), nullable=False),
    sa.Column('sleepover_only_weekday', sa.Integer(), nullable=False),
    sa.Column('sleepover_only_weekend', sa.Integer(), nullable=False),
    sa.Column('sleepover_extra_hour_over14', sa.Integer(), nullable=False),
    sa.Column('after17_weekday', sa.Integer(), nullable=False),
    sa.Column('after17_weekend', sa.Integer(), nullable=False),
    sa.Column('over9_weekday', sa.Integer(), nullable=False),
    sa.Column('over9_weekend', sa.Integer(), nullable=False),
    sa.Column('sleepover_start_hour', sa.Integer(), nullable=False),
    sa.Column('sleepover_end_hour', sa.Integer(), nullable=False),
    sa.Column('sleepover_after7_hourly', sa.Integer(), nullable=False),
    sa.Column('booking_fee_pct_1_5', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('booking_fee_pct_6_10', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('booking_fee_pct_10_plus', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('cancellation_fee_window_hours', sa.Integer(), nullable=False),
    sa.Column('overrun_hourly_weekday', sa.Integer(), nullable=False),
    sa.Column('overrun_hourly_weekend', sa.Integer(), nullable=False),
    sa.Column('overrun_hold_hours', sa.Integer(), nullable=False),
    sa.Column('payout_hold_hours', sa.Integer(), nullable=False),
    sa.Column('transport_fee_17_20', sa.Integer(), nullable=False),
    sa.Column('transport_fee_after_20', sa.Integer(), nullable=False),
    sa.Column('transport_threshold_1', sa.Integer(), nullable=False),
    sa.Column('transport_threshold_2', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('phone_alt', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('paystack_customer_code', sa.String(), nullable=True),
    sa.Column('paystack_auth_code', sa.String(), nullable=True),
    sa.Column('card_last4', sa.String(), nullable=True),
    sa.Column('card_brand', sa.String(), nullable=True),
    sa.Column('card_saved_at', sa.DateTime(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('last_initial', sa.String(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('admin_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('accepted_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_invites_email'), ['email'], unique=False)
        batch_op.create_index('ix_admin_invites_email_status', ['email', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_invites_token'), ['token'], unique=True)

    op.create_table('admin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('changed_fields', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_user_id', ['actor_user_id'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity'], unique=False)
        batch_op.create_index('ix_audit_logs_entity_id', ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index('ix_audit_logs_target_user_id', ['target_user_id'], unique=False)

    op.create_table('in_app_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nannies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('rating_demerit_pct', sa.Float(), nullable=False),
    sa.Column('cancellation_count', sa.Integer(), nullable=False),
    sa.Column('no_show_count', sa.Integer(), nullable=False),
    sa.Column('admin_review_flagged', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('suspension_lifted_at', sa.DateTime(), nullable=True),
    sa.Column('suspension_lifted_by', sa.Integer(), nullable=True),
    sa.Column('paystack_recipient_code', sa.String(), nullable=True),
    sa.Column('profile_complete', sa.Boolean(), nullable=False),
    sa.Column('availability_complete', sa.Boolean(), nullable=False),
    sa.Column('banking_complete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['suspension_lifted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('suburb', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('lat_round', sa.Float(), nullable=True),
    sa.Column('lng_round', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('location_confirm_version', sa.String(), nullable=True),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('suburb', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('location_label', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('kids_count', sa.Integer(), nullable=True),
    sa.Column('kids_ages_json', sa.Text(), nullable=True),
    sa.Column('desired_tag_ids_json', sa.Text(), nullable=True),
    sa.Column('home_language_id', sa.Integer(), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('family_photo_url', sa.String(), nullable=True),
    sa.Column('residence_type', sa.String(), nullable=True),
    sa.Column('access_flags_json', sa.Text(), nullable=True),
    sa.Column('booking_responsibilities', sa.Text(), nullable=True),
    sa.Column('booking_adult_present', sa.Text(), nullable=True),
    sa.Column('booking_reason', sa.Text(), nullable=True),
    sa.Column('booking_children_count', sa.Integer(), nullable=True),
    sa.Column('booking_meal_option', sa.Text(), nullable=True),
    sa.Column('booking_food_restrictions', sa.Text(), nullable=True),
    sa.Column('booking_dogs', sa.Text(), nullable=True),
    sa.Column('booking_disclaimer_basic_upkeep', sa.Boolean(), nullable=True),
    sa.Column('booking_disclaimer_medicine', sa.Boolean(), nullable=True),
    sa.Column('booking_disclaimer_extra_hours', sa.Boolean(), nullable=True),
    sa.Column('booking_disclaimer_transport', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('booking_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_user_id', sa.BigInteger(), nullable=False),
    sa.Column('nanny_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.Column('start_dt', sa.Text(), nullable=True),
    sa.Column('end_dt', sa.Text(), nullable=True),
    sa.Column('sleepover', sa.Boolean(), nullable=True),
    sa.Column('wage_cents', sa.Integer(), nullable=True),
    sa.Column('booking_fee_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('booking_fee_cents', sa.Integer(), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company_retained_cents', sa.Integer(), nullable=True),
    sa.Column('nanny_retained_cents', sa.Integer(), nullable=True),
    sa.Column('refund_cents', sa.Integer(), nullable=True),
    sa.Column('refund_status', sa.Text(), nullable=True),
    sa.Column('refund_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_failure_reason', sa.Text(), nullable=True),
    sa.Column('refund_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('refund_review_reason', sa.Text(), nullable=True),
    sa.Column('paystack_reference', sa.Text(), nullable=True),
    sa.Column('paystack_transaction_id', sa.Text(), nullable=True),
    sa.Column('paystack_refund_reference', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_status', sa.Text(), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('client_notes', sa.Text(), nullable=True),
    sa.Column('requested_nannies_count', sa.Integer(), nullable=True),
    sa.Column('created_by_admin_user_id', sa.BigInteger(), nullable=True),
    sa.Column('requested_starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_user_id', sa.BigInteger(), nullable=True),
    sa.Column('admin_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_reason', sa.Text(), nullable=True),
    sa.Column('replacement_required', sa.Boolean(), nullable=False),
    sa.Column('unaccepted_admin_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nanny_response_status', sa.Text(), nullable=True),
    sa.Column('nanny_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nanny_response_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("nanny_response_status IS NULL OR nanny_response_status IN ('pending','accepted','declined','deciding')", name='booking_requests_nanny_response_status_check'),
    sa.CheckConstraint("payment_status IN ('pending_payment','paid','cancelled')", name='booking_requests_payment_status_check'),
    sa.CheckConstraint("status IN ('tbc','pending_admin','approved','rejected','cancelled')", name='booking_requests_status_check'),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['parent_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['refund_reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nanny_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nanny_id', 'area_id', name='uq_nanny_area')
    )
    op.create_table('nanny_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nanny_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('start_dt', sa.Text(), nullable=True),
    sa.Column('end_dt', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='availability_time_check'),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nanny_availability', schema=None) as batch_op:
        batch_op.create_index('na_nanny_date_idx', ['nanny_id', 'date'], unique=False)

    op.create_table('nanny_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=False),
    sa.Column('account_number', sa.Text(), nullable=True),
    sa.Column('account_number_token', sa.Text(), nullable=True),
    sa.Column('bank_code', sa.Text(), nullable=False),
    sa.Column('bank_name', sa.Text(), nullable=True),
    sa.Column('paystack_recipient_code', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nanny_debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('balance_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nanny_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('passport_number', sa.String(), nullable=True),
    sa.Column('passport_expiry', sa.String(), nullable=True),
    sa.Column('passport_document_url', sa.String(), nullable=True),
    sa.Column('permit_status', sa.String(), nullable=True),
    sa.Column('work_permit', sa.Boolean(), nullable=True),
    sa.Column('work_permit_expiry', sa.String(), nullable=True),
    sa.Column('work_permit_document_url', sa.String(), nullable=True),
    sa.Column('waiver', sa.Boolean(), nullable=True),
    sa.Column('sa_id_number', sa.String(), nullable=True),
    sa.Column('sa_id_document_url', sa.String(), nullable=True),
    sa.Column('has_own_car', sa.Boolean(), nullable=True),
    sa.Column('has_drivers_license', sa.Boolean(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('current_job_availability', sa.String(), nullable=True),
    sa.Column('police_clearance_status', sa.String(), nullable=True),
    sa.Column('has_own_kids', sa.Boolean(), nullable=True),
    sa.Column('own_kids_details', sa.Text(), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('my_nanny_training_status', sa.String(), nullable=True),
    sa.Column('dog_preference', sa.String(), nullable=True),
    sa.Column('studying_details', sa.Text(), nullable=True),
    sa.Column('police_clearance_document_url', sa.String(), nullable=True),
    sa.Column('drivers_license_document_url', sa.String(), nullable=True),
    sa.Column('certificates_json', sa.Text(), nullable=True),
    sa.Column('previous_jobs_json', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('is_approved', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.String(), nullable=True),
    sa.Column('application_status', sa.String(), nullable=True),
    sa.Column('admin_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('suburb', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nanny_id')
    )
    op.create_table('parent_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_user_id', 'nanny_id', name='uq_parent_favorite')
    )
    with op.batch_alter_table('parent_favorites', schema=None) as batch_op:
        batch_op.create_index('ix_parent_favorites_nanny_id', ['nanny_id'], unique=False)
        batch_op.create_index('ix_parent_favorites_parent_user_id', ['parent_user_id'], unique=False)

    op.create_table('booking_pricing_snapshot',
    sa.Column('booking_request_id', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('hourly_rate_cents', sa.Integer(), nullable=False),
    sa.Column('fee_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('base_amount_cents', sa.Integer(), nullable=False),
    sa.Column('fee_amount_cents', sa.Integer(), nullable=False),
    sa.Column('total_amount_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('base_amount_cents >= 0', name='bps_base_amount_check'),
    sa.CheckConstraint('fee_amount_cents >= 0', name='bps_fee_amount_check'),
    sa.CheckConstraint('fee_pct >= 0 AND fee_pct <= 1', name='bps_fee_pct_check'),
    sa.CheckConstraint('hourly_rate_cents >= 0', name='bps_hourly_rate_check'),
    sa.CheckConstraint('total_amount_cents >= 0', name='bps_total_amount_check'),
    sa.CheckConstraint('total_minutes >= 0', name='bps_total_minutes_check'),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_request_id')
    )
    op.create_table('booking_request_slots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('booking_request_id', sa.BigInteger(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='booking_request_slots_time_check'),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_request_slots', schema=None) as batch_op:
        batch_op.create_index('brs_request_id_idx', ['booking_request_id'], unique=False)
        batch_op.create_index('brs_starts_at_idx', ['starts_at'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_request_id', sa.BigInteger(), nullable=True),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('client_user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('start_dt', sa.String(), nullable=True),
    sa.Column('end_dt', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location_mode', sa.String(), nullable=True),
    sa.Column('location_label', sa.String(), nullable=True),
    sa.Column('formatted_address', sa.String(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(), nullable=True),
    sa.Column('check_in_lat', sa.Float(), nullable=True),
    sa.Column('check_in_lng', sa.Float(), nullable=True),
    sa.Column('check_in_distance_m', sa.Float(), nullable=True),
    sa.Column('check_in_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('check_in_confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('check_out_at', sa.DateTime(), nullable=True),
    sa.Column('check_out_lat', sa.Float(), nullable=True),
    sa.Column('check_out_lng', sa.Float(), nullable=True),
    sa.Column('check_out_distance_m', sa.Float(), nullable=True),
    sa.Column('check_out_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('check_out_confirmed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_actor_role', sa.String(), nullable=True),
    sa.Column('cancellation_actor_user_id', sa.Integer(), nullable=True),
    sa.Column('google_calendar_event_id', sa.String(), nullable=True),
    sa.Column('google_calendar_synced_at', sa.DateTime(), nullable=True),
    sa.Column('google_calendar_sync_error', sa.Text(), nullable=True),
    sa.Column('overrun_minutes', sa.Integer(), nullable=True),
    sa.Column('overrun_amount_cents', sa.Integer(), nullable=True),
    sa.Column('overrun_status', sa.String(), nullable=True),
    sa.Column('overrun_paystack_ref', sa.Text(), nullable=True),
    sa.Column('overrun_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('overrun_queried_at', sa.DateTime(), nullable=True),
    sa.Column('overrun_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('overrun_resolved_by', sa.Integer(), nullable=True),
    sa.Column('overrun_hold_until', sa.DateTime(), nullable=True),
    sa.Column('overrun_disputed', sa.Boolean(), nullable=False),
    sa.Column('overrun_dispute_raised_at', sa.DateTime(), nullable=True),
    sa.Column('overrun_resolution', sa.Text(), nullable=True),
    sa.Column('overrun_released_at', sa.DateTime(), nullable=True),
    sa.Column('payout_hold_until', sa.DateTime(), nullable=True),
    sa.Column('payout_released_at', sa.DateTime(), nullable=True),
    sa.Column('payout_amount_cents', sa.Integer(), nullable=True),
    sa.Column('payout_debt_deducted_cents', sa.Integer(), nullable=False),
    sa.Column('payout_disputed', sa.Boolean(), nullable=False),
    sa.Column('payout_dispute_raised_at', sa.DateTime(), nullable=True),
    sa.Column('payout_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('payout_resolved_by', sa.Integer(), nullable=True),
    sa.Column('payout_resolution', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_requests.id'], ),
    sa.ForeignKeyConstraint(['cancellation_actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['check_in_confirmed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['check_out_confirmed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ),
    sa.ForeignKeyConstraint(['overrun_resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payout_resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nanny_demerit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('demerit_pct', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('cumulative_demerit_pct', sa.Float(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('applied_by', sa.Text(), nullable=False),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversed_by', sa.Integer(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking_requests.id'], ),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nanny_profile_languages',
    sa.Column('nanny_profile_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['nanny_profile_id'], ['nanny_profiles.id'], ),
    sa.PrimaryKeyConstraint('nanny_profile_id', 'language_id')
    )
    op.create_table('nanny_profile_qualifications',
    sa.Column('nanny_profile_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nanny_profile_id'], ['nanny_profiles.id'], ),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], ),
    sa.PrimaryKeyConstraint('nanny_profile_id', 'qualification_id')
    )
    op.create_table('nanny_profile_tags',
    sa.Column('nanny_profile_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nanny_profile_id'], ['nanny_profiles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['nanny_tags.id'], ),
    sa.PrimaryKeyConstraint('nanny_profile_id', 'tag_id')
    )
    op.create_table('client_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('parent_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('stars >= 1 AND stars <= 5', name='client_reviews_stars_check'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_reviews', schema=None) as batch_op:
        batch_op.create_index('client_reviews_approved_idx', ['approved'], unique=False)
        batch_op.create_index('client_reviews_booking_id_idx', ['booking_id'], unique=False)
        batch_op.create_index('client_reviews_nanny_id_idx', ['nanny_id'], unique=False)
        batch_op.create_index('client_reviews_parent_user_id_idx', ['parent_user_id'], unique=False)

    op.create_table('debt_deduction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('amount_deducted_cents', sa.Integer(), nullable=False),
    sa.Column('balance_after_cents', sa.Integer(), nullable=False),
    sa.Column('deducted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['nanny_debt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('stars >= 1 AND stars <= 5', name='reviews_stars_check'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index('reviews_approved_idx', ['approved'], unique=False)
        batch_op.create_index('reviews_created_at_idx', ['created_at'], unique=False)
        batch_op.create_index('reviews_nanny_id_idx', ['nanny_id'], unique=False)
        batch_op.create_index('reviews_parent_user_id_idx', ['parent_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index('reviews_parent_user_id_idx')
        batch_op.drop_index('reviews_nanny_id_idx')
        batch_op.drop_index('reviews_created_at_idx')
        batch_op.drop_index('reviews_approved_idx')

    op.drop_table('reviews')
    op.drop_table('debt_deduction_log')
    with op.batch_alter_table('client_reviews', schema=None) as batch_op:
        batch_op.drop_index('client_reviews_parent_user_id_idx')
        batch_op.drop_index('client_reviews_nanny_id_idx')
        batch_op.drop_index('client_reviews_booking_id_idx')
        batch_op.drop_index('client_reviews_approved_idx')

    op.drop_table('client_reviews')
    op.drop_table('nanny_profile_tags')
    op.drop_table('nanny_profile_qualifications')
    op.drop_table('nanny_profile_languages')
    op.drop_table('nanny_demerit_log')
    op.drop_table('bookings')
    with op.batch_alter_table('booking_request_slots', schema=None) as batch_op:
        batch_op.drop_index('brs_starts_at_idx')
        batch_op.drop_index('brs_request_id_idx')

    op.drop_table('booking_request_slots')
    op.drop_table('booking_pricing_snapshot')
    with op.batch_alter_table('parent_favorites', schema=None) as batch_op:
        batch_op.drop_index('ix_parent_favorites_parent_user_id')
        batch_op.drop_index('ix_parent_favorites_nanny_id')

    op.drop_table('parent_favorites')
    op.drop_table('nanny_profiles')
    op.drop_table('nanny_debt')
    op.drop_table('nanny_bank_accounts')
    with op.batch_alter_table('nanny_availability', schema=None) as batch_op:
        batch_op.drop_index('na_nanny_date_idx')

    op.drop_table('nanny_availability')
    op.drop_table('nanny_areas')
    op.drop_table('booking_requests')
    op.drop_table('parent_profiles')
    op.drop_table('parent_locations')
    op.drop_table('notification_log')
    op.drop_table('nannies')
    op.drop_table('in_app_notifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_target_user_id')
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index('ix_audit_logs_entity_id')
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_actor_user_id')
        batch_op.drop_index('ix_audit_logs_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_profiles_id'))

    op.drop_table('admin_profiles')
    with op.batch_alter_table('admin_invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_invites_token'))
        batch_op.drop_index('ix_admin_invites_email_status')
        batch_op.drop_index(batch_op.f('ix_admin_invites_email'))

    op.drop_table('admin_invites')
    op.drop_table('users')
    op.drop_table('qualifications')
    op.drop_table('pricing_settings')
    op.drop_table('nanny_tags')
    op.drop_table('languages')
    op.drop_table('areas')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
