"use client";
import { AuthenticatedPage } from "@/components/authenticated-page";
import { apiJson } from "@/lib/api";
import { Clock, LoaderCircle, MapPin, Wallet } from "lucide-react";
import { useEffect, useState } from "react";

type RequestRow={id:number;parent_name:string;start_dt:string;end_dt:string;location_label?:string;location_address?:string;distance_km?:number;wage_cents?:number;nanny_response_status:string;days_required?:number};
export default function Requests(){
  const [rows,setRows]=useState<RequestRow[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<number|null>(null);const [message,setMessage]=useState("");
  async function load(){setLoading(true);try{const data=await apiJson<{results:RequestRow[]}>("/nannies/me/booking-requests?include_accepted=true");setRows(data.results||[]);}catch(err){setMessage(err instanceof Error?err.message:"Unable to load requests.");}finally{setLoading(false);}}
  useEffect(()=>{apiJson<{results:RequestRow[]}>("/nannies/me/booking-requests?include_accepted=true").then((data)=>setRows(data.results||[])).catch((err)=>setMessage(err instanceof Error?err.message:"Unable to load requests.")).finally(()=>setLoading(false));},[]);
  async function respond(id:number,response:"deciding"|"declined"){setBusy(id);try{await apiJson(`/nannies/me/booking-requests/${id}/respond`,{method:"POST",body:JSON.stringify({response,note:response==="declined"?"Not available":"Reviewing schedule"})});await load();}catch(err){setMessage(err instanceof Error?err.message:"Unable to update request.");}finally{setBusy(null);}}
  async function accept(id:number){setBusy(id);try{await apiJson(`/nannies/me/booking-requests/${id}/accept`,{method:"POST",body:"{}"});await load();setMessage("Booking accepted.");}catch(err){setMessage(err instanceof Error?err.message:"Unable to accept booking.");}finally{setBusy(null);}}
  return <AuthenticatedPage>{()=> <div className="mx-auto max-w-5xl"><div className="eyebrow">Work opportunities</div><h1 className="display mt-2 text-4xl sm:text-5xl">Booking requests.</h1><p className="mt-3 text-[var(--muted)]">Review the family, schedule, distance and earnings before committing.</p>{message&&<div role="status" className="mt-5 rounded-xl bg-[var(--blue-pale)] p-4 text-sm">{message}</div>}{loading?<div className="mt-12 flex justify-center"><LoaderCircle className="animate-spin"/></div>:rows.length?<div className="mt-7 grid gap-4">{rows.map((row)=><article className="card p-5" key={row.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-bold">Care for {row.parent_name}</h2><div className="mt-3 grid gap-2 text-sm text-[var(--muted)]"><div className="flex items-center gap-2"><Clock size={15}/>{new Date(row.start_dt).toLocaleString("en-ZA",{dateStyle:"medium",timeStyle:"short"})} – {new Date(row.end_dt).toLocaleTimeString("en-ZA",{hour:"2-digit",minute:"2-digit"})}</div><div className="flex items-center gap-2"><MapPin size={15}/>{row.location_label||row.location_address||"Booking location"}{row.distance_km!=null?` · ${row.distance_km} km`:""}</div><div className="flex items-center gap-2"><Wallet size={15}/>Estimated earnings R{((row.wage_cents||0)/100).toFixed(2)}</div></div></div><span className="pill capitalize">{row.nanny_response_status.replaceAll("_"," ")}</span></div>{row.nanny_response_status!=="accepted"&&<div className="mt-5 flex flex-wrap gap-3 border-t border-[var(--line)] pt-5"><button className="btn-primary" disabled={busy===row.id} onClick={()=>accept(row.id)}>Accept booking</button><button className="btn-secondary" disabled={busy===row.id} onClick={()=>respond(row.id,"deciding")}>Still deciding</button><button className="btn-quiet text-red-700" disabled={busy===row.id} onClick={()=>respond(row.id,"declined")}>Decline</button></div>}</article>)}</div>:<div className="card mt-7 p-10 text-center"><h2 className="text-xl font-bold">No open requests right now</h2><p className="mt-2 text-[var(--muted)]">New opportunities that match your location and availability will appear here.</p></div>}</div>}</AuthenticatedPage>;
}
