"use client";

import { AuthenticatedPage } from "@/components/authenticated-page";
import { apiJson } from "@/lib/api";
import { MailPlus, ShieldCheck, UserCog, X } from "lucide-react";
import { FormEvent, startTransition, useEffect, useState } from "react";

type Level = "operations" | "finance" | "superadmin";
type TeamData = { admins: { id: number; name: string; email: string; is_active: boolean; access_level: Level }[]; pending_invites: { id: number; email: string; access_level: Level; reason?: string; expires_at: string }[] };
const roleCopy: Record<Level, string> = { operations: "Bookings, candidates, users and communication", finance: "Finance, payouts, refunds and communication", superadmin: "Full platform, trust, settings, audit and team access" };

export default function TeamPage() { return <AuthenticatedPage>{(role) => role === "admin" ? <TeamWorkspace/> : <Denied/>}</AuthenticatedPage>; }
function TeamWorkspace() {
  const [data, setData] = useState<TeamData>({ admins: [], pending_invites: [] }); const [email, setEmail] = useState(""); const [level, setLevel] = useState<Level>("operations"); const [reason, setReason] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { setData(await apiJson<TeamData>("/admin/team")); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load team access."); } }
  useEffect(() => { startTransition(() => { void load(); }); }, []);
  async function invite(event: FormEvent) { event.preventDefault(); setMessage(""); try { await apiJson("/admin/invites", { method: "POST", body: JSON.stringify({ email, access_level: level, reason }) }); setEmail(""); setReason(""); setMessage("Invitation sent."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to send invitation."); } }
  async function changeAccess(id: number, access_level: Level) { try { await apiJson(`/admin/team/${id}/access`, { method: "PATCH", body: JSON.stringify({ access_level }) }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to update access."); } }
  async function cancel(id: number) { try { await apiJson(`/admin/invites/${id}/cancel`, { method: "POST" }); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to cancel invitation."); } }
  return <div className="mx-auto max-w-[1450px]"><div className="eyebrow">Security & people</div><h1 className="display mt-2 text-4xl sm:text-5xl">Team access.</h1><p className="mt-3 max-w-3xl text-[var(--muted)]">Give each teammate only the access they need. Sensitive finance, audit and platform settings are enforced by the server.</p>{message && <div className="mt-6 rounded-2xl bg-[var(--blue-pale)] p-4 font-semibold">{message}</div>}
  <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_.72fr]"><section className="card p-6"><div className="flex items-center gap-3"><UserCog className="text-[var(--blue)]"/><h2 className="text-2xl font-bold">Administrators</h2></div><div className="mt-6 grid gap-3">{data.admins.map((admin) => <div key={admin.id} className="rounded-2xl border border-[var(--line)] p-4 sm:flex sm:items-center sm:justify-between"><div><div className="font-bold">{admin.name}</div><div className="text-sm text-[var(--muted)]">{admin.email}</div></div><select className="field mt-3 !w-auto sm:mt-0" value={admin.access_level} onChange={(event) => void changeAccess(admin.id, event.target.value as Level)}>{Object.keys(roleCopy).map((item) => <option key={item} value={item}>{item}</option>)}</select></div>)}</div></section>
  <div className="grid content-start gap-6"><form className="card p-6" onSubmit={invite}><div className="flex items-center gap-3"><MailPlus className="text-[var(--blue)]"/><h2 className="text-xl font-bold">Invite teammate</h2></div><label className="mt-5 block text-sm font-bold">Email address<input className="field mt-2" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required/></label><label className="mt-4 block text-sm font-bold">Access level<select className="field mt-2" value={level} onChange={(e) => setLevel(e.target.value as Level)}>{Object.entries(roleCopy).map(([value, copy]) => <option key={value} value={value}>{value}: {copy}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Reason (optional)<textarea className="field mt-2 min-h-24" value={reason} onChange={(e) => setReason(e.target.value)}/></label><button className="btn-primary mt-5" type="submit">Send invitation</button></form>
  <section className="card p-6"><h2 className="text-xl font-bold">Pending invitations</h2><div className="mt-4 grid gap-3">{data.pending_invites.length === 0 && <p className="text-[var(--muted)]">No invitations are waiting.</p>}{data.pending_invites.map((invite) => <div key={invite.id} className="flex items-center justify-between rounded-xl bg-[var(--blue-pale)] p-3"><div><div className="font-bold">{invite.email}</div><div className="text-xs capitalize text-[var(--muted)]">{invite.access_level}</div></div><button className="btn-quiet !px-2" onClick={() => void cancel(invite.id)} aria-label="Cancel invitation"><X size={18}/></button></div>)}</div></section></div></div></div>;
}
function Denied() { return <div className="card mx-auto max-w-xl p-8 text-center"><ShieldCheck className="mx-auto"/><h1 className="mt-4 text-2xl font-bold">Superadmin access required</h1></div>; }
